---
- hosts: all
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    nginx_path: /home/ec2-user/nginx
    html_path: /home/ec2-user/nginx/html
  tasks:
    - name: Download artifact
      shell: |
        aws s3 cp s3://{{bucket_name}}/{{file_name}} {{nginx_path}}/build.tar.gz
        rm -rf {{html_path}}/*

    - name: "Wait until the download finish"
      wait_for:
        path: "{{nginx_path}}/build.tar.gz"

    - name: "unarchive package"
      unarchive:
        src: "{{nginx_path}}/build.tar.gz"
        dest: "{{nginx_path}}"
        remote_src: yes

    - name: "move unarchived package and delete unnecessary files"
      shell: |
        mv {{nginx_path}}/build {{html_path}}
        rm {{nginx_path}}/build.tar.gz
