---
- hosts: "{{project}}-{{service}}"

  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    access_key: "{{accessKey}}"
    secret_key: "{{secretKey}}"
    profile: "{{profile}}"
    project_name: "{{project}}-{{service}}"
    tag: "{{tag}}"
    ecr_url: 880047505389.dkr.ecr.ap-northeast-1.amazonaws.com

  tasks:
    - name: aws ecr login
      shell: |
        export AWS_ACCESS_KEY_ID={{access_key}}
        export AWS_SECRET_ACCESS_KEY={{secret_key}}
        aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin {{ecr_url}}
      ignore_errors: yes

    - name: pull image
      command: docker pull "{{ecr_url}}/{{project_name}}":"{{tag}}"

    - name: run container deploy eureka server.
      command: docker run -d --network=host --env PROFILE="{{profile}}" "{{ecr_url}}/{{project_name}}":"{{tag}}"

    - name: stop spring server in container.
      shell: |
        docker exec -it $(cat {{service}}_container_id) pkill java
      ignore_errors: yes

    - name: Waiting for disconnect eureka.
      pause:
        seconds: 10

    - name: delete container.
      shell: |
        docker rm -f $(cat {{service}}_container_id)
      ignore_errors: yes

    - name: save container id
      shell: docker ps | grep "{{ecr_url}}/{{project_name}}":"{{tag}}" | awk '{print $1}' > {{service}}_container_id

    - name: Remove all dangling images
      command: docker image prune -af
      ignore_errors: yes
